// <auto-generated />
using System;
using EmployeeManagement.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241023144944_added_seeded_data_for_company_department")]
    partial class added_seeded_data_for_company_department
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8542),
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8548),
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8549),
                            Name = "Google"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8550),
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8551),
                            Name = "Nestle"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8552),
                            Name = "ExxonMobile"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8661),
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8663),
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8664),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8665),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8666),
                            Name = "R&D"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8667),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 4,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8668),
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 4,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8669),
                            Name = "Production"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 5,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8670),
                            Name = "Culinary"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 5,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8671),
                            Name = "Supply Chain"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 6,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8672),
                            Name = "Sustainability"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 6,
                            CreatedDate = new DateTime(2024, 10, 23, 18, 49, 44, 339, DateTimeKind.Utc).AddTicks(8673),
                            Name = "Business Development"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Department", b =>
                {
                    b.HasOne("EmployeeManagement.Domain.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
