// <auto-generated />
using System;
using EmployeeManagement.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241024170415_added_configurations_for_tables")]
    partial class added_configurations_for_tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6521),
                            Name = "Pasha Bank"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6528),
                            Name = "Socar"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6529),
                            Name = "Azerenergy"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6530),
                            Name = "AzerGold"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6531),
                            Name = "Azersun Holding"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6531),
                            Name = "Azercell"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6660),
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6662),
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6663),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6664),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6665),
                            Name = "R&D"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6666),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 4,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6667),
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 4,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6667),
                            Name = "Production"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 5,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6669),
                            Name = "Culinary"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 5,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6670),
                            Name = "Supply Chain"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 6,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6670),
                            Name = "Customer Service"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 6,
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6671),
                            Name = "Business Development"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1985, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6697),
                            DepartmentId = 1,
                            Name = "Anar",
                            Surname = "Hüseynov"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1990, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6702),
                            DepartmentId = 2,
                            Name = "Aysel",
                            Surname = "Quliyeva"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2000, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6703),
                            DepartmentId = 3,
                            Name = "Murad",
                            Surname = "Əliyev"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1995, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6705),
                            DepartmentId = 1,
                            Name = "Nigar",
                            Surname = "Səfərova"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1992, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6707),
                            DepartmentId = 8,
                            Name = "Elvin",
                            Surname = "İsmayılov"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1996, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6708),
                            DepartmentId = 2,
                            Name = "Leyla",
                            Surname = "Əliyeva"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1987, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6709),
                            DepartmentId = 3,
                            Name = "Rəşad",
                            Surname = "Əhmədov"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1993, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6711),
                            DepartmentId = 4,
                            Name = "Günel",
                            Surname = "Əliyeva"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1984, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6712),
                            DepartmentId = 5,
                            Name = "Vüsal",
                            Surname = "Əkbərov"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1989, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6713),
                            DepartmentId = 6,
                            Name = "İlqar",
                            Surname = "Məmmədov"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1991, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6714),
                            DepartmentId = 7,
                            Name = "Sevinc",
                            Surname = "Rzayeva"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1983, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6715),
                            DepartmentId = 3,
                            Name = "Taleh",
                            Surname = "Qasımov"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1994, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6717),
                            DepartmentId = 11,
                            Name = "Zaur",
                            Surname = "Abdullayev"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1986, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6718),
                            DepartmentId = 4,
                            Name = "Kamran",
                            Surname = "Nəsibov"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1992, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6719),
                            DepartmentId = 12,
                            Name = "Elçin",
                            Surname = "Nəzərov"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(1989, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6720),
                            DepartmentId = 2,
                            Name = "Aynur",
                            Surname = "Həsənova"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(1985, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6721),
                            DepartmentId = 3,
                            Name = "Fuad",
                            Surname = "Babayev"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(1982, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6723),
                            DepartmentId = 5,
                            Name = "Namiq",
                            Surname = "Əliyev"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1993, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6724),
                            DepartmentId = 4,
                            Name = "Orxan",
                            Surname = "Hüseynov"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1995, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6725),
                            DepartmentId = 1,
                            Name = "Rəna",
                            Surname = "Mustafayeva"
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(1984, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6726),
                            DepartmentId = 10,
                            Name = "Şəhriyar",
                            Surname = "Həsənov"
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(1988, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6727),
                            DepartmentId = 4,
                            Name = "Ülviyyə",
                            Surname = "İsmayılova"
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(1994, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6729),
                            DepartmentId = 5,
                            Name = "Toğrul",
                            Surname = "Hüseynov"
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(1986, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6730),
                            DepartmentId = 1,
                            Name = "Rəşad",
                            Surname = "Bayramov"
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(1991, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6731),
                            DepartmentId = 2,
                            Name = "Kənan",
                            Surname = "Cəfərov"
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(1987, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6732),
                            DepartmentId = 3,
                            Name = "Zəka",
                            Surname = "Mustafayev"
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(1993, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6733),
                            DepartmentId = 4,
                            Name = "Fərid",
                            Surname = "Xəlilov"
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(1985, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6734),
                            DepartmentId = 9,
                            Name = "Eldar",
                            Surname = "Salmanov"
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(1992, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 10, 24, 21, 4, 15, 128, DateTimeKind.Utc).AddTicks(6736),
                            DepartmentId = 1,
                            Name = "Sabir",
                            Surname = "Babayev"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Department", b =>
                {
                    b.HasOne("EmployeeManagement.Domain.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeManagement.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
