// <auto-generated />
using System;
using EmployeeManagement.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241023161638_added_employee_table")]
    partial class added_employee_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8257),
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8265),
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8265),
                            Name = "Google"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8266),
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8266),
                            Name = "Nestle"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8267),
                            Name = "ExxonMobile"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8354),
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8356),
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8357),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8357),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8358),
                            Name = "R&D"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8358),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 4,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8359),
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 4,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8359),
                            Name = "Production"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 5,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8361),
                            Name = "Culinary"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 5,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8361),
                            Name = "Supply Chain"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 6,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8361),
                            Name = "Sustainability"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 6,
                            CreatedDate = new DateTime(2024, 10, 23, 20, 16, 37, 858, DateTimeKind.Utc).AddTicks(8362),
                            Name = "Business Development"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Department", b =>
                {
                    b.HasOne("EmployeeManagement.Domain.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeManagement.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
